### PR TITLE
Added create function for Comments.

### PR DESCRIPTION
**Pull request by Triasto**
The api for bitbucket has changed through time and now it's possible to create a comment, hence this change.

https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D/comments#post

### CODE REVIEW

**Comment by m1guelpf** [comment]
@Triasto Why did you close this?

**Comment by Triasto** [comment]
> @Triasto Why did you close this?

We need the changes in our current project and found that there's more code missing.
So we're using my fork for the moment and I'll create a new pull request when we're done :)

**Comment by GrahamCampbell** [comment]
When I wrote this package on Monday 4th April 2018, all of the API was implemented. Unfortunately Bitbucket don't seem to have a change log, which makes things hard to update.

**Comment by Triasto** [comment]
> When I wrote this package on Monday 4th April 2018, all of the API was implemented. Unfortunately Bitbucket don't seem to have a change log, which makes things hard to update.

Yup, no problem at all :) When someone needs something that's not there then we can just update things to make it work ;)

I'll create a new PR somewhere near the end of the month.

**Pull request closed without merging**
